---
title: 'Military Officers Pursuing PhDs: Are Three Years Enough?'
author: Michael E. Flynn
date: '2022-05-24'
slug: []
categories:
  - Academia
  - Blogging
  - Military
  - teaching
  - PhD
tags:
  - academia
  - blogging
  - doctoral degrees
  - doctorate
  - jobs
  - military
  - phd
  - policy
subtitle: ''
summary: ''
authors: []
lastmod: '2022-05-24T18:55:33-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

**tl;dr: My goal here is to catalog what ended up being a fairly wide ranging (and I think informative) series of tweets from lots of different people on timelines for military students pursuing their PhD in political science or related fields. A lot of folks brought a lot of different perspectives to this question, but Twitter isn't always the best format for organizing material in a clear and coherent way.**

## Background

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

I don't know who in the military is responsible for creating these programs that are sending officers out with the expectation that they're going to readily get a PhD in three years, but stop it.

</p>

--- Michael Flynn (@flynnpolsci) <a href="https://twitter.com/flynnpolsci/status/1469352835225731084?ref_src=twsrc%5Etfw">December 10, 2021</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```


Are three years enough time for a military student to complete a PhD program in political science or related fields? The original post that sparked this exchange is below, but I'll include other key followup posts, too.

Many active duty military officers who are interested in pursuing a PhD do so through some different avenues. I'm not going to claim expert knowledge as to all the pathways, but one that often pops up is the Advanced Strategic Planning and Policy Program (ASP3). The US Army's School of Advanced Military Studies [describes the ASP3 program](https://usacac.army.mil/organizations/cace/cgsc/sams) as follows:

> The Advanced Strategic Planning and Policy Program is a multi-year program that prepares field-grade officers for service as strategic planners through a combination of practical experience, professional military education, and a doctorate from a civilian university. Once selected for the program, officers apply to doctoral programs at respected American universities in a liberal arts field of study related to strategy. They spend up to two years in graduate school satisfying all course and exam requirements leading to acceptance as a doctoral candidate. During these years, officers will also attend professional military education at the School of Advanced Military Studies (SAMS) at Fort Leavenworth, Kansas studying history, strategic theory, and the practice of strategic planning. Officers will then serve a developmental assignment in a strategic planning position. Those officers selected for battalion or brigade command will be afforded the opportunity. After the developmental assignment, the officer will spend one year working full time on the dissertation at SAMS or another suitable location and then be available for utilization as a strategic planner.

As outlined in the description, the general idea is to allocate three years to the completion of a PhD---two years of coursework and one year of dissertation writing. Contrast this with civilian programs in the US that often follow a path like this:

1.  Coursework. Usually 2-3 years of coursework, with a combination of general field seminars, methods seminars, and more focused subfield seminars. Specific requirements will vary by department. For example, we were required to take a set of core seminars in all subfields, a sequence of five quantitative methods courses (3 in statistics/econometrics, and two in game theory). We didn't offer a qualitative methods course, I now wish we did, but you can imagine that extends, or makes more variable, what a given methods sequence might look like.
2.  Exams. We had Qualifying Exams in year 1 or 2, and everyone took comprehensive exams after five semesters of coursework,
3.  The prospectus. Basically your plan for your dissertation that you write and defend. Some are shorter (15-25 pages) and others can be longer (mine was \~60 pages).
4.  The dissertation. Again, there are different models to follow here. Some write the "three paper" model, others follow more of a book model. A lot of this depends on advisory, department, program, topic, etc.

There are a number of difficulties in assessing timelines here as we're not exactly comparing apples to apples. Here are a few points to consider that might alter baseline expectations:

1.  Civilian students are often working as teaching or research assistants (TA/RA) while taking courses and working on the dissertation.
2.  Military students often have full funding, meaning they're not required to work as an TA/RA.
3.  Ultimate career trajectories aren't the same. Military students are often going to go back to the force while civilian students are likely training for a career in academia, NGOs, the private sector, government, etc.
4.  The academic job market can introduce distortions into the timeline as there are a lot of external factors that affect the date of completion, and at a certain point you're often mostly done and waiting to get a job before you officially "complete" the program.

I'm going to try to block off the main arguments for and against this time frame below. Let me also declare a couple of caveats before diving into more detail. First, because I'm the one writing this post and assembling the material there's inevitably going to be a bit more content pertaining to my own viewpoint here. I came out of a political science program with more of a quantitative/statistical focus in terms of research methodology. I'm also currently the Director of Security Studies at Kansas State University---a program that's run by both political science and history departments. We deal overwhelmingly with Army officers. Last, I can't include all of the responses, but if you're interested you should comb through the thread to check out what others think (especially some of the respondents who are or were active duty and dealing with this very issue).

## What's a PhD for, Anyway?

First, let me explain what I think the value of the PhD is, and why (presumably) people would want to get one. There are a couple of dimensions to this question. First, a PhD is a research degree---it's a degree focused on evaluating existing knowledge and producing new knowledge.

Do you *need* one to do research? No, but getting one offers you an opportunity to set aside a prolonged period of time to train under established experts and to learn as a part of a broader cohort/community. In the social sciences the emphasis is often on learning to synthesize theoretical and empirical insights from various sources, and using these insights to develop your own research program. For military officers, specifically, it offers them an opportunity to acquire skills that are perhaps not readily available through their regular training and educational processes.

Second, for officers who are pursuing a PhD at a civilian university it offers them a chance to get out of the bubble of the military. Taking time to embed oneself in a civilian institution, to learn from civilian experts, and to work alongside civilians in their broader cohort. More succinctly, there's a socialization aspect here that may not be as readily available in venues that are predominately military students.

Overall, it's about having the time to really immerse yourself in material and a community that is focused primarily on developing research skills and building knowledge. For people pursuing an academic path these skills and experiences will be beneficial for obvious reasons. And military students who may soon retire and/or transition into the private sector or government will find these skills useful for lots of the same reasons.

But what about military students who will likely remain in the military? Lots of the skills students develop while pursuing graduate education at civilian institutions will continue to be of use for students once they return to their day jobs in the military. Often the questions that motivate these students during their PhD studies arise *from* their time in uniform. Ideally they will return to their jobs better equipped to tackle some of these problems.

I once had a student who had been deployed to Afghanistan and was tasked with assessing the efficacy of certain measures on insurgent activities. This experience worked out great for a measurement paper assignment in one of his seminars. Another student coming from a logistics background did some great work on the relationship between transportation infrastructure and the efficacy of UN peacekeeping operations.

Ultimately these students seem to have been able to effectively use their time to improve develop skills to allow them to better perform the tasks they were already being asked to do in the military.

The question then is what amount of time is "enough" to distinguish the PhD from other opportunities, like an MA degree? Students will cover a lot of the same ground in a one or two-year MA program as compared to a three-year PhD program, so what is the value added that makes an accelerated PhD program "worth it"?

## Is Three Years Enough Time to Earn a PhD?

So can it be done in three years? I've given this some thought in the intervening months and the short answer is "Yes, it *can* be done, but it's not ideal".

To be clear, I don't mean "ideal" from an academic-training-other-academics perspective. I mean ideal from the perspective of maximizing student success, ensuring sufficient value added from the PhD program, and return on investment from a taxpayer dollar perspective. I'll return to address these issues below.

Ultimately I think this path can work really well for some people, but I worry that we're leaving a lot on the table, and even a fourth year would go a long ways towards optimizing outcomes.

I'll come back to these concerns below. For now, I'll divide this section into two sections to capture the general arguments in support of, or in opposition to, this time frame. Let's tackle some of the supportive arguments first.

### Yes, it's Enough

First, let's go over some of the arguments in favor. Several respondents to the thread think three years as enough, or nearly enough. One particularly important feature that some folks noted is that military officers who choose to pursue these programs are often highly motivated and further along in their careers.

Philip Hultquist, a professor at the School of Advanced Military Studies at Ft. Leavenworth, discusses some of his experiences with military students pursuing PhDs in this sub-thread.

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

Michael, I shared your skepticism when I first learned of it too, but since working <a href="https://twitter.com/us_sams?ref_src=twsrc%5Etfw">@us_sams</a> I've seen it done. I'm on a diss committee and have given advice to several students. Though I teach in a different program I can provide some context. A quick 🧵

</p>

--- Philip Hultquist (@HultquistPhilip) <a href="https://twitter.com/HultquistPhilip/status/1469429078960783362?ref_src=twsrc%5Etfw">December 10, 2021</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
Philip notes that for military officers pursuing a PhD, the PhD *is* their full time job. They don't need to worry about funding, grants, RA/TA responsibilities, etc. The military's financial backing and ability to focus strictly on the degree program is a huge benefit with respect to finishing an accelerated timeline.

Importantly, in addition to selecting for high achievers, these students typically have an MA degree in hand already when they enter a PhD program. Our own Security Studies program allows students to transfer up to 30 hours of coursework from a previous MA degree towards PhD coursework. So these students are 1) already familiar with graduate-level work, 2) probably have some prior exposure to the relevant literature, and 3) possibly already have some sort of methods training.

This prior experience can be a determining factor. Sheena Greitens, a professor at the LBJ School at UT-Austin, makes a good point about the fact that faculty at civilian universities should not automatically discount the prior educational and research experience military officers may have.

This impulse seems to reflect a difference between US and European programs, where the former typically require PhD students with an MA to repeat coursework and the latter will accept MA experience towards the doctorate. Elsewhere in this conversation she also makes the point that dealing with these timelines may require programs and/or advisers to make adjustments to their approach and expectations.

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

LBJ requires a masters first. Similarly, when I did the Oxford MPhil, DPhil was a 3-yr option after that. Doesn't work for every project (didn't for mine, so I came back to US!). But the idea that everyone needs 5+ yrs *regardless of prep beforehand* strikes me as too rigid.

</p>

--- Sheena Chestnut Greitens (@SheenaGreitens) <a href="https://twitter.com/SheenaGreitens/status/1469511200627122186?ref_src=twsrc%5Etfw">December 11, 2021</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
Furthermore, people in the military may have pressing considerations beyond the degree itself. Nick Frazier offers some thoughts on career considerations that make longer program duration less feasible/desirable for the Army and military officers. In particular, he highlights the lengthy time period that officers "owe" to the military subsequent to finishing their PhD, and also difficulties assessing an officer's time in graduate school when it comes to promotions.

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

I don't know who in the military is responsible for creating these programs that are sending officers out with the expectation that they're going to readily get a PhD in three years, but stop it.

</p>

--- Michael Flynn (@flynnpolsci) <a href="https://twitter.com/flynnpolsci/status/1469352835225731084?ref_src=twsrc%5Etfw">December 10, 2021</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
I don't take this to mean that PhD timelines should be shortened to provide special accommodations to the US military. Rather, I think this is akin to the mantra "a good dissertation is a finished dissertation." If military officers *can* finish in three years, there are *very* good reasons to do so.

In short, military students who are pursuing PhDs are often selected because they have the relevant prior experience, are high achievers, have financial backing that alleviates pressures others face, and have strong personal and professional incentives to succeed. Furthermore, the expectation that longer timelines are *necessary* is partly a function of more rigid programs and faculty advisers.

### No, It's Not Enough

The section title is a slight misrepresentation of my views on this since I think it's possible and fine for some folks. More accurately, I think a four year PhD track would be desirable for lots of reasons. As I said above, I think there are lots of benefits to military officers pursuing PhDs, and I think we need to make sure that there is sufficient value added to ensure the degree is meaningfully different from another MA degree.

At the most basic level three years is, well, only three years. That's just not a lot of time for things to happen, no matter how driven a student may be.

First, two years of coursework is probably fine. That's a little bit less than what a lot of PhD programs require, it's probably OK if we're generally selecting students who have already received an MA degree in the chosen field prior to enrolling in a PhD. In such cases we're totaling around 4 years of coursework, which is more than enough.

My concerns really kick in with the prospectus and dissertation-writing process (but a little before, too). One year is not a lot of time to write and defend a prospectus, and then write and defend a dissertation. Can it be done? Sure, but it assumes *a lot* of things go right. And I think this is where the pressure really falls on admissions committees and faculty to try to screen for those candidates who are most likely to succeed under the given framework.

But here's the thing I worry about---this doesn't allow a lot of room for failure. And I don't mean completely failing the program and being forced to leave. Research and the production of knowledge are inherently messy processes, and not everything goes right on the first go around. Lots of smart people fail at getting a PhD because it's not just about reading and retaining knowledge, but about synthesizing insights from existing work and using those to create something new. Coding rules require revising, inclusion criteria may need a tweak, whatever. Anyone who has collected original data as a part of their dissertation (or any project) can probably attest to this fact. And this is coming from a guy who had to write two prospectuses because my first one was hot garbage.

Again, can these hurdles be overcome? Yes, but I worry that for those who don't fit the neat and clean model, or those who have some unexpected hurdles arise, will be pushed over their time limits or never selected to begin with. Maybe they'll still finish, but I'm willing to bet there's much more uncertainty once they're back in their regular jobs.

Some of this is echoed in tweets by Will Winecoff, an associate professor at the University of Indiana, and a [followup tweet by Dan Drezner](https://twitter.com/dandrezner/status/1469449803906093057?s=20&t=X10ZgyjMo4X5Nr_ydduYcw), a professor at Tufts University. Both note that while the students they've worked with are strong, many (most?) don't finish within three years.

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

In my experience it doesn't get done in 3 years, but it does get done. These folks are highly-motivated and have long track records of diligence. I have a lot of respect for the ones who enter these programs.

</p>

--- W. K. Winecoff (@whinecough) <a href="https://twitter.com/whinecough/status/1469447342352912394?ref_src=twsrc%5Etfw">December 10, 2021</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
I also worry that this limits the variability in what, and how, people research during the PhD process. Relying on existing sources, whether it's quantitative or qualitative data, or more historical work or case studies, is suitable for lots of dissertations. But there are also lots of civilian dissertations that require field work, interviews, and other research tools that require more time and likely draw out the pre-writing process. Even lots of more quantitative dissertations may require more substantial methods training.

Close advising, using seminar papers as chapters, and a three-paper dissertation model may be great for getting people across the finish line in the allotted time, but it seems to me that they necessarily preclude certain educational/research pathways and impose a substantial degree of homogeneity on the type of research military officers are able to conduct. I worry we're leaving a lot of potentially good work on the table as a result.

This timeline also imposes a barrier for military students who seek to deepen methodological expertise. For civilian students who are going into academia they also have plenty of time *after* getting the PhD to spend more time learning/developing methods, improving language skills, spending time in their chosen country or region, etc. Military officers may not have this flexibility, and so maximizing what they can learn while still pursuing the PhD is perhaps more important for them.

I think some folks will call back to the previous section and note that the time spent working on the MA also also contributes to these goals. Maybe. Lots of students at the MA level don't necessarily know that they'll be going on to pursue a PhD. Professional and research interests also change over time. As I note above, this presumes lots of things go right. So it's not clear to me that the cumulative time is equivalent to allowing more time to pursue the PhD.

The point here is not to simply be training military officers as academic researchers. The point is that many of their projects are motivated by the substantive concerns of their jobs, and we should want to train them as effectively as possible so the PhD brings real value added when they return to those jobs. Learning about research design, measurement, interview techniques, etc., are all skills that map directly onto what a lot of our students have done on previous deployments.

Last, beyond having additional time to develop their own skills, the time where military students are interfacing with civilian faculty and students is, itself, highly valuable. You learn a lot about intellectual collaboration outside of seminars while working alongside your colleagues. Also, I think there's tremendous normative value in these programs because they break down the barriers between the civilian and military worlds.

## Takeaways

So who's right? ¯\\\_(ツ)\_/¯

I think there are lots of reasons why a three year track can make sense for some people, and they can indeed be very successful. But I think even an additional year would bring tremendous benefits to everyone involved for lots of reasons.

But saying a four year track is better should not be taken as a call to scrap these relationships. Ultimately I think having military students in our programs and giving them an opportunity work alongside civilians is much better than not having them around at all. We get lots of bright students coming through our program, and lots of other folks have shared similar assessments/experiences. The challenge under the current system, then, is to figure out how faculty and programs can work with military students to maximize their chances of success, and what they take away, while we have them.
